//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Doctor
    {
        public int DocId { get; set; }
        public string DoctorName { get; set; }
        public string Qualification { get; set; }
        public string Specialization { get; set; }
        public string Experience { get; set; }
        public string Gender { get; set; }
        public string Contact { get; set; }
        public string Aadhar { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public string AvailabilityDates { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string DoctorPwd { get; set; }
    }
}
