//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Patient
    {
        public int PId { get; set; }
        public string Pname { get; set; }
        public string Gender { get; set; }
        public string Contact { get; set; }
        public string Reason { get; set; }
        public string Medication { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Diagnosis { get; set; }
        public string temp { get; set; }
        public string Sugar_BP { get; set; }
        public string Advice { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
